import os
import requests
from dotenv import load_dotenv

load_dotenv()

ODOO_URL = os.getenv("ODOO_URL")
ODOO_KEY = os.getenv("ODOO_KEY")
DB_NAME = "smartcardai"
UID = 2

headers = {"Content-Type": "application/json"}

def create_odoo_record(model, data):
    payload = {
        "jsonrpc": "2.0",
        "method": "call",
        "id": 1,
        "params": {
            "service": "object",
            "method": "execute_kw",
            "args": [
                DB_NAME,
                UID,
                ODOO_KEY,
                model,
                "create",
                [data]
            ]
        }
    }
    url = f"{ODOO_URL}/jsonrpc"
    r = requests.post(url, headers=headers, json=payload)
    return r.status_code, r.text

sample_data = {
    "stock.picking": {
        "partner_id": 1,
        "picking_type_id": 1,
        "location_id": 1,
        "location_dest_id": 1
    },
    "account.move": {
        "move_type": "out_invoice",
        "partner_id": 1,
        "invoice_date": "2024-01-01",
        "invoice_line_ids": [(0, 0, {"product_id": 1, "quantity": 1, "price_unit": 100})]
    },
    "mrp.production": {
        "product_id": 1,
        "product_qty": 1,
        "bom_id": 1,
        "product_uom_id": 1,
        "location_src_id": 1,
        "location_dest_id": 1
    },
    "purchase.order": {
        "partner_id": 1,
        "order_line": [(0, 0, {"product_id": 1, "product_qty": 1, "price_unit": 100})]
    },
    "crm.lead": {
        "name": "Test Lead",
        "partner_id": 1,
        "email_from": "test@example.com",
        "description": "Generated by test script"
    }
}

for model, data in sample_data.items():
    status, response = create_odoo_record(model, data)
    print(f"{model} ➜ Status: {status}")
    print(response)
    print("-" * 50)