services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_db
    environment:
      SA_PASSWORD: ${SA_PASSWD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./init/init.sql:/init.sql
    command: /opt/mssql/bin/sqlservr

  app:
    build: .
    container_name: flask_app
    depends_on:
      - db
    environment:
      MsSQLserver: ${MsSQLserver}
      MsSQLdb: ${MsSQLdb}
      MsSQLuser: ${MsSQLuser}
      MsSQLpassword: ${SA_PASSWD}
    ports:
      - "5000:5000"
    command: >
      /bin/bash -c "
        python3 init_db.py &&
        python3 main.py
      "

volumes:
  mssql_data:
