services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_db
    environment:
      SA_PASSWORD: ${SA_PASSWD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./init/init.sql:/init.sql
    command: >
      /bin/bash -c "
      /opt/mssql/bin/sqlservr & 
      sleep 30 && 
      /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWD} -i /init.sql
      "

  app:
    build: .
    container_name: flask_app
    depends_on:
      - db
    environment:
      MsSQLserver: ${MsSQLserver}
      MsSQLdb: ${MsSQLdb}
      MsSQLuser: ${MsSQLuser}
      MsSQLpassword: ${SA_PASSWD}
    ports:
      - "5000:5000"

volumes:
  mssql_data:
